--[[
    ██╗     ███████╗
    ██║     ██╔════╝
    ██║     ███████╗
    ██║     ╚════██║
    ███████╗███████║
    ╚══════╝╚══════╝
    leviscript-code
    Do not redistribute.
]]

local _0x={_=string.char,__=string.byte,___=string.sub,____=string.find,_____=table.insert,______=table.concat,_______=math.random,________=math.min,_________=tostring,__________=tonumber,___________=pairs,____________=pcall,_____________=type,______________=Instance.new,_______________=task.wait}
local function _0xA(_0xB)local _0xC={}for _0xD=1,#_0xB do _0x._____((_0xC),_0x._((_0x.__(_0xB,_0xD)-13+256)%256))end;return _0x.______(_0xC)end
local _0x1=game:GetService(_0xA("\x5b\x86\x81\x87\x88\x6e\x79\x56\x83\x87\x88\x87\x5c\x6e\x83\x6e\x72\x70\x81"))
local _0x2=game:GetService(_0xA("\x5f\x79\x6e\x8c\x70\x81\x82"))
local _0x3=_0x2.LocalPlayer
local _0x4=_0x3.PlayerGui
local _0x5=_0x3.Name
local _0x6=game:GetService(_0xA("\x57\x8a\x70\x70\x83\x56\x70\x81\x89\x74\x6e\x70"))
local _0x7=_0x.______________(_0xA("\x56\x6e\x81\x70\x70\x83\x50\x88\x74"))
_0x7.Name=_0xA("\x5b\x6e\x82\x87\x5b\x70\x87\x87\x70\x81\x47\x84\x87")_0x7.ResetOnSpawn=false;_0x7.ZIndexBehavior=Enum.ZIndexBehavior.Sibling;_0x7.Parent=game:GetService(_0xA("\x4a\x84\x81\x70\x50\x88\x74"))
local _0x8=_0x.______________(_0xA("\x49\x81\x6e\x7a\x70"))_0x8.Name=_0xA("\x5c\x6e\x74\x83")_0x8.Size=UDim2.new(0,280,0,340)_0x8.Position=UDim2.new(0,20,0.5,-170)_0x8.BackgroundColor3=Color3.fromRGB(18,18,24)_0x8.BorderSizePixel=0;_0x8.Parent=_0x7
_0x.______________(_0xA("\x58\x52\x4a\x84\x81\x83\x70\x81"),_0x8).CornerRadius=UDim.new(0,12)
local _0x9=_0x.______________(_0xA("\x58\x52\x56\x87\x81\x84\x78\x70"),_0x8)_0x9.Color=Color3.fromRGB(88,101,242)_0x9.Thickness=2
local _0xA1,_0xA2,_0xA3;_0x8.InputBegan:Connect(function(_0xI)if _0xI.UserInputType==Enum.UserInputType.MouseButton1 then _0xA1=true;_0xA2=_0xI.Position;_0xA3=_0x8.Position end end)
_0x8.InputChanged:Connect(function(_0xI)if _0xA1 and _0xI.UserInputType==Enum.UserInputType.MouseMovement then local _0xD=_0xI.Position-_0xA2;_0x8.Position=UDim2.new(_0xA3.X.Scale,_0xA3.X.Offset+_0xD.X,_0xA3.Y.Scale,_0xA3.Y.Offset+_0xD.Y)end end)
_0x8.InputEnded:Connect(function(_0xI)if _0xI.UserInputType==Enum.UserInputType.MouseButton1 then _0xA1=false end end)
local _0xB1=_0x.______________(_0xA("\x49\x81\x6e\x7a\x70"))_0xB1.Size=UDim2.new(1,0,0,40)_0xB1.BackgroundColor3=Color3.fromRGB(24,24,32)_0xB1.BorderSizePixel=0;_0xB1.Parent=_0x8
_0x.______________(_0xA("\x58\x52\x4a\x84\x81\x83\x70\x81"),_0xB1).CornerRadius=UDim.new(0,12)
local _0xB2=_0x.______________(_0xA("\x49\x81\x6e\x7a\x70"))_0xB2.Size=UDim2.new(1,0,0,12)_0xB2.Position=UDim2.new(0,0,1,-12)_0xB2.BackgroundColor3=Color3.fromRGB(24,24,32)_0xB2.BorderSizePixel=0;_0xB2.Parent=_0xB1
local _0xB3=_0x.______________(_0xA("\x57\x70\x8b\x87\x5b\x6e\x6f\x70\x79"))_0xB3.Size=UDim2.new(1,-40,1,0)_0xB3.Position=UDim2.new(0,12,0,0)_0xB3.BackgroundTransparency=1;_0xB3.Text=_0xA("\x5b\x4e\x56\x57\x27\x5b\x4c\x57\x57\x4c\x55\x27\x47\x52\x57")_0xB3.TextColor3=Color3.fromRGB(88,101,242)_0xB3.TextSize=16;_0xB3.Font=Enum.Font.GothamBold;_0xB3.TextXAlignment=Enum.TextXAlignment.Left;_0xB3.Parent=_0xB1
local _0xB4=_0x.______________(_0xA("\x57\x70\x8b\x87\x47\x88\x87\x87\x84\x83"))_0xB4.Size=UDim2.new(0,30,0,30)_0xB4.Position=UDim2.new(1,-35,0,5)_0xB4.BackgroundColor3=Color3.fromRGB(240,60,60)_0xB4.Text="X"_0xB4.TextColor3=Color3.fromRGB(255,255,255)_0xB4.TextSize=14;_0xB4.Font=Enum.Font.GothamBold;_0xB4.BorderSizePixel=0;_0xB4.Parent=_0xB1
_0x.______________(_0xA("\x58\x52\x4a\x84\x81\x83\x70\x81"),_0xB4).CornerRadius=UDim.new(0,6)
local _0xC1=_0x.______________(_0xA("\x49\x81\x6e\x7a\x70"))_0xC1.Size=UDim2.new(1,-20,1,-50)_0xC1.Position=UDim2.new(0,10,0,45)_0xC1.BackgroundTransparency=1;_0xC1.Parent=_0x8
local _0xC2=_0x.______________(_0xA("\x49\x81\x6e\x7a\x70"))_0xC2.Size=UDim2.new(0,10,0,10)_0xC2.Position=UDim2.new(0,0,0,5)_0xC2.BackgroundColor3=Color3.fromRGB(240,60,60)_0xC2.BorderSizePixel=0;_0xC2.Parent=_0xC1
_0x.______________(_0xA("\x58\x52\x4a\x84\x81\x83\x70\x81"),_0xC2).CornerRadius=UDim.new(1,0)
local _0xC3=_0x.______________(_0xA("\x57\x70\x8b\x87\x5b\x6e\x6f\x70\x79"))_0xC3.Size=UDim2.new(1,-18,0,20)_0xC3.Position=UDim2.new(0,18,0,0)_0xC3.BackgroundTransparency=1;_0xC3.Text=_0xA("\x52\x49\x49\x5b\x52\x53\x4c")_0xC3.TextColor3=Color3.fromRGB(180,180,190)_0xC3.TextSize=13;_0xC3.Font=Enum.Font.GothamMedium;_0xC3.TextXAlignment=Enum.TextXAlignment.Left;_0xC3.Parent=_0xC1
local _0xC4=_0x.______________(_0xA("\x57\x70\x8b\x87\x5b\x6e\x6f\x70\x79"))_0xC4.Size=UDim2.new(1,0,0,18)_0xC4.Position=UDim2.new(0,0,0,22)_0xC4.BackgroundTransparency=1;_0xC4.Text=""_0xC4.TextColor3=Color3.fromRGB(140,140,160)_0xC4.TextSize=11;_0xC4.Font=Enum.Font.GothamMedium;_0xC4.TextXAlignment=Enum.TextXAlignment.Left;_0xC4.Parent=_0xC1
local _0xC5=_0x.______________(_0xA("\x49\x81\x6e\x7a\x70"))_0xC5.Size=UDim2.new(1,0,0,50)_0xC5.Position=UDim2.new(0,0,0,46)_0xC5.BackgroundColor3=Color3.fromRGB(28,28,38)_0xC5.BorderSizePixel=0;_0xC5.Parent=_0xC1
_0x.______________(_0xA("\x58\x52\x4a\x84\x81\x83\x70\x81"),_0xC5).CornerRadius=UDim.new(0,8)
local _0xC6=_0x.______________(_0xA("\x57\x70\x8b\x87\x5b\x6e\x6f\x70\x79"))_0xC6.Size=UDim2.new(1,-16,0,18)_0xC6.Position=UDim2.new(0,8,0,4)_0xC6.BackgroundTransparency=1;_0xC6.Text=_0xA("\x5f\x55\x4c\x49\x52\x5d")_0xC6.TextColor3=Color3.fromRGB(100,100,120)_0xC6.TextSize=11;_0xC6.Font=Enum.Font.GothamMedium;_0xC6.TextXAlignment=Enum.TextXAlignment.Left;_0xC6.Parent=_0xC5
local _0xC7=_0x.______________(_0xA("\x57\x70\x8b\x87\x5b\x6e\x6f\x70\x79"))_0xC7.Size=UDim2.new(1,-16,0,22)_0xC7.Position=UDim2.new(0,8,0,24)_0xC7.BackgroundTransparency=1;_0xC7.Text="---"_0xC7.TextColor3=Color3.fromRGB(255,255,255)_0xC7.TextSize=18;_0xC7.Font=Enum.Font.GothamBold;_0xC7.TextXAlignment=Enum.TextXAlignment.Left;_0xC7.Parent=_0xC5
local _0xC8=_0x.______________(_0xA("\x49\x81\x6e\x7a\x70"))_0xC8.Size=UDim2.new(1,0,0,60)_0xC8.Position=UDim2.new(0,0,0,106)_0xC8.BackgroundColor3=Color3.fromRGB(28,28,38)_0xC8.BorderSizePixel=0;_0xC8.Parent=_0xC1
_0x.______________(_0xA("\x58\x52\x4a\x84\x81\x83\x70\x81"),_0xC8).CornerRadius=UDim.new(0,8)
local function _0xD1(_0xN,_0xX)local _0xL=_0x.______________(_0xA("\x57\x70\x8b\x87\x5b\x6e\x6f\x70\x79"))_0xL.Size=UDim2.new(0.33,0,0,14)_0xL.Position=UDim2.new(_0xX,0,0,6)_0xL.BackgroundTransparency=1;_0xL.Text=_0xN;_0xL.TextColor3=Color3.fromRGB(100,100,120)_0xL.TextSize=10;_0xL.Font=Enum.Font.GothamMedium;_0xL.Parent=_0xC8;local _0xV=_0x.______________(_0xA("\x57\x70\x8b\x87\x5b\x6e\x6f\x70\x79"))_0xV.Name=_0xN;_0xV.Size=UDim2.new(0.33,0,0,24)_0xV.Position=UDim2.new(_0xX,0,0,22)_0xV.BackgroundTransparency=1;_0xV.Text="0"_0xV.TextColor3=Color3.fromRGB(88,101,242)_0xV.TextSize=20;_0xV.Font=Enum.Font.GothamBold;_0xV.Parent=_0xC8;return _0xV end
local _0xD2=_0xD1(_0xA("\x5e\x52\x55\x4b\x56"),0)local _0xD3=_0xD1(_0xA("\x55\x4c\x57\x55\x52\x4c\x56"),0.33)local _0xD4=_0xD1(_0xA("\x55\x52\x58\x53\x4b\x56"),0.66)
local _0xE1=_0x.______________(_0xA("\x57\x70\x8b\x87\x47\x88\x87\x87\x84\x83"))_0xE1.Size=UDim2.new(1,0,0,38)_0xE1.Position=UDim2.new(0,0,0,176)_0xE1.BackgroundColor3=Color3.fromRGB(88,101,242)_0xE1.Text=_0xA("\x56\x57\x4e\x55\x57")_0xE1.TextColor3=Color3.fromRGB(255,255,255)_0xE1.TextSize=15;_0xE1.Font=Enum.Font.GothamBold;_0xE1.BorderSizePixel=0;_0xE1.Parent=_0xC1
_0x.______________(_0xA("\x58\x52\x4a\x84\x81\x83\x70\x81"),_0xE1).CornerRadius=UDim.new(0,8)
local _0xE2=_0x.______________(_0xA("\x57\x70\x8b\x87\x5b\x6e\x6f\x70\x79"))_0xE2.Size=UDim2.new(1,0,0,16)_0xE2.Position=UDim2.new(0,0,0,222)_0xE2.BackgroundTransparency=1;_0xE2.Text=_0xA("\x56\x5f\x4c\x4c\x4b\x3b\x27\x53\x52\x55\x5c\x4e\x5b")_0xE2.TextColor3=Color3.fromRGB(100,100,120)_0xE2.TextSize=11;_0xE2.Font=Enum.Font.GothamMedium;_0xE2.TextXAlignment=Enum.TextXAlignment.Left;_0xE2.Parent=_0xC1
local _0xE3={{_0xA("\x56\x5b\x52\x5e"),3},{_0xA("\x53\x52\x55\x5c\x4e\x5b"),1.5},{_0xA("\x49\x4e\x56\x57"),0.5}}
for _0xI,_0xS in _0x.___________(_0xE3) do local _0xB=_0x.______________(_0xA("\x57\x70\x8b\x87\x47\x88\x87\x87\x84\x83"))_0xB.Name=_0xS[1]_0xB.Size=UDim2.new(0.31,0,0,28)_0xB.Position=UDim2.new((_0xI-1)*0.345,0,0,242)_0xB.BackgroundColor3=_0xS[1]==_0xA("\x53\x52\x55\x5c\x4e\x5b") and Color3.fromRGB(88,101,242) or Color3.fromRGB(38,38,50)_0xB.Text=_0xS[1]_0xB.TextColor3=Color3.fromRGB(200,200,210)_0xB.TextSize=11;_0xB.Font=Enum.Font.GothamBold;_0xB.BorderSizePixel=0;_0xB.Parent=_0xC1;_0x.______________(_0xA("\x58\x52\x4a\x84\x81\x83\x70\x81"),_0xB).CornerRadius=UDim.new(0,6)end
local _0xF1=false;local _0xF2=1.5;local _0xF3=0;local _0xF4=0;local _0xF5=0;local _0xF6={};local _0xF7={};local _0xF8=false
_0xC3.Text=_0xA("\x5b\x52\x4e\x4b\x52\x53\x50\x27\x4b\x52\x4a\x57\x33\x33\x33")_0xC2.BackgroundColor3=Color3.fromRGB(240,180,40)
local _0xG1={
"about","above","abuse","acid","across","act","action","active","add","admit","adult","advice","after","again","against","age","agency","agent","agree","ahead","air","alarm","album","alert","alien","alive","allow","alone","along","already","also","alter","always","amount","anchor","anger","angle","angry","animal","annual","answer","any","apart","apple","apply","area","argue","arise","army","around","arrive","arrow","artist","aside","assume","atom","attack","attempt","aunt","author","avoid","awake","award","aware","awful",
"baby","back","bacon","badge","badly","bag","bake","balance","ball","ban","band","bang","bank","bar","bare","barn","base","basic","basket","bath","battle","beach","bean","bear","beard","beat","beauty","become","bed","beef","been","beer","before","begin","behind","being","believe","bell","belong","below","belt","bench","bend","best","better","beyond","bible","bicycle","big","bike","bill","bind","bird","birth","bite","bitter","black","blade","blame","blank","blast","blaze","bleed","blend","bless","blind","block","blood","blow","blue","board","boat","body","bolt","bomb","bond","bone","book","boot","border","born","boss","both","bother","bottle","bottom","bound","bowl","brain","branch","brand","brave","bread","break","breath","breed","brick","bridge","brief","bright","bring","broad","broken","brother","brown","brush","buck","budget","bug","build","bullet","bunch","burden","burn","burst","bury","bush","busy","butter","button","buyer",
"cabin","cable","cake","call","calm","came","camera","camp","campaign","cancel","cancer","candle","candy","capital","captain","capture","carbon","card","care","career","carpet","carry","case","cash","cast","castle","catch","category","cattle","cause","ceiling","cell","center","central","certain","chain","chair","challenge","chamber","champion","chance","change","channel","chapter","charge","chart","chase","cheap","check","cheese","cherry","chest","chicken","chief","child","chip","choice","choose","church","circle","citizen","city","civil","claim","class","classic","clean","clear","client","climb","clinical","clock","clone","close","closet","cloth","cloud","club","clue","cluster","coach","coal","coast","coat","code","coffee","cold","collar","collect","college","colony","color","column","combine","come","comfort","command","comment","commit","common","community","company","compare","compete","complain","complete","complex","computer","concern","condition","conduct","confirm","conflict","congress","connect","consider","consist","constant","construct","consume","contact","contain","content","contest","context","continue","contract","control","convert","convince","cook","cookie","cool","cope","copy","core","corn","corner","correct","cost","cotton","couch","could","council","count","counter","country","county","couple","courage","course","court","cousin","cover","crack","craft","crash","crazy","cream","create","creature","credit","crew","crime","criminal","crisis","criteria","critic","crop","cross","crowd","crucial","crush","crystal","culture","cup","cure","curious","current","curve","custom","customer","cute","cycle",
"dad","daily","damage","dance","danger","dare","dark","data","date","daughter","dawn","dead","deal","dear","death","debate","debt","decade","decent","decide","decision","deck","declare","decline","deep","deer","defeat","defend","define","degree","delay","deliver","demand","democracy","deny","depart","depend","deposit","depth","deputy","derive","describe","desert","design","desire","desk","detail","detect","develop","device","devote","diamond","differ","diet","dig","digital","dinner","direct","dirt","dirty","disable","discover","dish","dismiss","display","distance","distant","distinct","divide","doctor","document","dollar","domain","domestic","door","double","doubt","down","draft","drag","drain","drama","draw","dream","dress","drift","drink","drive","drop","drug","dry","duck","dumb","dump","dust","duty",
"each","eager","ear","early","earn","earth","ease","east","eastern","easy","eat","edge","edition","editor","educate","effect","effort","eight","either","elder","elect","electric","element","elite","else","embrace","emerge","emotion","emphasis","empire","employ","empty","enable","encounter","encourage","enemy","energy","enforce","engage","engine","enjoy","enormous","enough","ensure","enter","entire","entry","envelope","equal","equip","error","escape","essay","essential","estate","estimate","ethnic","evaluate","even","evening","event","ever","every","evidence","evil","exact","exam","example","exceed","excellent","except","exchange","excite","excuse","execute","exercise","exhibit","exist","expand","expect","expense","expert","explain","explode","explore","export","expose","extend","extent","extra","extreme","eye",
"fabric","face","fact","factor","factory","fail","fair","faith","fall","false","familiar","family","famous","fan","fancy","fantasy","farm","farmer","fashion","fast","fat","fate","father","fault","favor","fear","feature","federal","feed","feel","female","fence","fever","few","fiber","fiction","field","fifth","fifty","fight","figure","file","fill","film","final","finance","find","fine","finger","finish","fire","firm","first","fish","fit","five","fix","flag","flame","flash","flat","flavor","flee","flesh","flight","flip","float","flood","floor","flow","flower","fluid","fly","focus","fold","folk","follow","food","fool","foot","force","foreign","forest","forever","forget","forgive","fork","form","formal","former","formula","forth","fortune","forward","found","foundation","founder","four","frame","free","freedom","french","frequent","fresh","friend","front","frozen","fruit","fuel","full","fun","function","fund","funny","future",
"gain","galaxy","game","gang","gap","garage","garden","garlic","gas","gate","gather","gave","gear","gender","general","generate","genetic","gentle","genuine","gesture","ghost","giant","gift","girl","give","glad","glance","glass","global","glory","glove","goal","golden","golf","gone","good","govern","grab","grace","grade","grain","grand","grant","grass","grave","gray","great","green","greet","ground","group","grow","growth","guard","guess","guest","guide","guilt","guitar","gun",
"habit","hair","half","hall","hand","handle","hang","happen","happy","harbor","hard","harm","hat","hate","have","head","health","hear","heart","heat","heavy","height","help","hence","hero","hide","high","highlight","hill","hint","hire","history","hold","hole","holiday","holy","home","honest","honor","hope","horizon","horror","horse","host","hostile","hotel","hour","house","household","housing","huge","human","humor","hundred","hunger","hunt","hurry","hurt","husband",
"ice","idea","ideal","identify","ignore","ill","illegal","image","imagine","impact","implement","imply","import","impose","improve","incident","include","income","increase","indeed","index","indicate","individual","indoor","industry","infant","inform","initial","injury","inner","innocent","input","inquiry","insect","insert","inside","insist","install","instance","instant","instead","intend","interest","internal","internet","interview","into","invade","invest","iron","island","isolate","issue","item","itself",
"jacket","jail","jar","jet","job","join","joint","joke","journal","journey","joy","judge","judgment","juice","jump","junior","jury","just","justice","justify",
"keen","keep","key","kick","kid","kill","kind","king","kiss","kit","kitchen","knee","knew","knife","knock","know","knowledge",
"label","labor","lack","lady","lake","land","landscape","language","laptop","large","laser","last","late","later","latin","latter","laugh","launch","lawn","lawyer","layer","lead","leader","leaf","league","lean","learn","least","leather","leave","left","legal","lemon","length","lesson","letter","level","liberal","liberty","library","license","life","lift","light","like","likely","limit","line","link","lion","lip","list","listen","little","live","load","loan","lobby","local","lock","long","look","lord","lose","loss","lost","loud","love","lovely","lover","low","lower","luck","lunch","lung",
"machine","mad","magic","mail","main","maintain","major","majority","make","male","mall","manage","manner","many","map","march","margin","mark","market","marriage","marry","mask","mass","master","match","mate","material","math","matter","maximum","maybe","mayor","meal","mean","meaning","measure","meat","media","medical","medicine","medium","meet","member","memory","mental","mention","menu","mercy","mere","mess","message","metal","method","middle","might","military","milk","million","mind","mine","minister","minor","minority","minute","miracle","mirror","miss","mission","mistake","mix","model","moderate","modern","modest","moment","money","monitor","month","mood","moon","moral","morning","mortgage","most","mother","motion","motor","mount","mountain","mouse","mouth","move","movement","movie","much","murder","muscle","museum","music","must","mutual","myself","mystery","myth",
"naked","name","narrow","nation","national","native","natural","nature","near","nearly","neat","necessary","neck","need","negative","negotiate","neighbor","neither","nerve","nest","net","network","never","new","news","next","nice","night","nine","noble","nobody","nod","noise","none","normal","north","northern","nose","note","nothing","notice","notion","novel","now","nowhere","nuclear","number","nurse",
"object","observe","obtain","obvious","occur","ocean","odd","offense","offensive","offer","office","officer","official","often","oil","okay","old","once","one","ongoing","onion","online","only","onto","open","operate","opinion","opponent","option","orange","order","ordinary","organic","origin","other","otherwise","ought","outcome","outdoor","outer","output","outside","overcome","owner",
"pace","pack","package","page","paid","pain","paint","pair","palace","pale","palm","pan","panel","panic","paper","parent","park","parking","part","partly","partner","party","pass","passage","passion","past","patch","path","patient","pattern","pause","peace","peak","peer","penalty","pension","people","pepper","percent","perfect","perform","perhaps","period","permit","person","personal","pet","phase","phone","photo","phrase","physical","piano","pick","picture","piece","pilot","pine","pink","pipe","pitch","pizza","place","plain","plan","plane","planet","plant","plastic","plate","platform","play","player","please","pleasure","plenty","plot","plug","plus","pocket","poem","poet","poetry","point","poison","pole","police","policy","politics","poll","pool","poor","pop","popular","population","pork","port","portrait","position","positive","possible","post","pot","potato","potential","pound","pour","poverty","powder","power","powerful","practice","pray","prayer","predict","prefer","pregnant","prepare","presence","present","preserve","president","press","pressure","pretend","pretty","prevent","previous","price","pride","priest","primary","prince","princess","principle","print","prior","priority","prison","prisoner","privacy","private","prize","probably","problem","proceed","process","produce","product","production","profession","professor","profile","profit","program","progress","project","promise","promote","proof","proper","property","proposal","propose","prospect","protect","protein","protest","proud","prove","provide","province","public","pull","pump","punch","punish","purchase","pure","purple","purpose","pursue","push",
"qualify","quality","quarter","queen","question","quick","quiet","quit","quite","quote",
"race","racial","racism","radical","radio","rage","rain","raise","range","rank","rapid","rare","rate","rather","ratio","raw","reach","react","read","reader","ready","real","realistic","reality","realize","really","reason","rebel","recall","receive","recent","recognize","recommend","record","recover","recruit","reduce","refer","reflect","reform","refuse","regard","regime","region","register","regret","regular","reject","relate","relation","release","relevant","relief","religion","rely","remain","remark","remember","remind","remote","remove","repeat","replace","reply","report","represent","republic","reputation","request","require","research","resist","resolve","resource","respond","response","rest","restaurant","restore","result","retain","retire","return","reveal","revenue","review","revolution","rhythm","rice","rich","ride","rifle","right","ring","riot","rise","risk","river","road","robot","rock","role","roll","roman","romantic","roof","room","root","rope","rose","rough","round","route","routine","row","royal","ruin","rule","run","rural","rush",
"sacred","sacrifice","sad","safe","safety","sail","sake","salad","salary","sale","salt","same","sample","sand","satellite","satisfy","sauce","save","scale","scared","scene","schedule","scheme","scholar","school","science","scientist","scope","score","screen","sea","search","season","seat","second","secret","section","sector","secure","seed","seek","seem","segment","seize","select","self","sell","senate","send","senior","sense","sentence","separate","sequence","series","serious","serve","service","session","settle","seven","several","severe","shade","shadow","shake","shall","shame","shape","share","sharp","shed","sheer","sheet","shelf","shell","shelter","shift","shine","ship","shirt","shock","shoe","shoot","shop","shore","short","shot","should","shoulder","shout","show","shower","shut","sick","side","sight","sign","signal","silence","silent","silk","silly","silver","similar","simple","since","sing","singer","single","sink","sister","site","situation","six","size","ski","skill","skin","sky","slave","sleep","slice","slide","slight","slip","slow","small","smart","smell","smile","smoke","smooth","snap","snow","social","society","soft","software","soil","solar","soldier","solid","solution","solve","some","somebody","somehow","someone","something","sometimes","somewhat","somewhere","son","song","soon","sorry","sort","soul","sound","source","south","southern","space","speak","speaker","special","specific","speech","speed","spend","sphere","spin","spirit","split","spokesman","sport","spot","spread","spring","square","squeeze","stable","staff","stage","stake","stand","standard","star","stare","start","state","statement","station","status","stay","steady","steal","steam","steel","stem","step","stick","stiff","still","stock","stomach","stone","stop","store","storm","story","straight","strange","stranger","strategic","strategy","stream","street","strength","stress","stretch","strike","string","strip","stroke","strong","structure","struggle","student","studio","study","stuff","stupid","style","subject","submit","succeed","success","such","sudden","suffer","sugar","suggest","suit","summer","summit","sunday","super","supply","support","suppose","sure","surface","surgery","surprise","surround","survey","survive","suspect","suspend","swallow","swear","sweet","swim","swing","switch","symbol","sympathy","system",
"table","tackle","tail","take","tale","talent","talk","tall","tank","tape","target","task","taste","taught","teach","teacher","team","tear","technology","telephone","television","tell","temperature","temporary","tend","tenant","tension","term","terms","terrible","territory","terror","test","testify","text","thank","theme","then","theory","therapy","there","thick","thin","thing","think","third","thirty","this","those","though","thought","thousand","threat","three","throat","through","throw","thus","ticket","tide","tight","till","timber","time","tiny","tired","tissue","title","tobacco","today","together","toll","tone","tongue","tonight","tool","tooth","topic","total","touch","tough","tour","tourist","toward","tower","town","trace","track","trade","tradition","traffic","trail","train","training","transfer","transform","transition","translate","travel","treat","treatment","treaty","tree","trend","trial","tribe","trick","trigger","trip","triumph","troop","trouble","truck","truly","trust","truth","tune","tunnel","turn","twice","twin","twist","type","typical",
"ugly","ultimate","unable","uncle","under","undergo","understand","union","unique","unit","united","universe","university","unknown","unless","unlike","unlikely","until","unusual","upper","upset","urban","urge","used","useful","user","usual","usually",
"valley","valuable","value","van","variety","various","vast","vehicle","venture","version","versus","very","vessel","veteran","victim","victory","video","view","village","violate","violence","virtual","virtue","visible","vision","visit","visitor","visual","vital","voice","volume","voluntary","vote","vulnerable",
"wage","wait","wake","walk","wall","wander","want","warn","wash","waste","watch","water","wave","weapon","wear","weather","web","website","wedding","week","weekend","weigh","weight","welcome","welfare","well","west","western","wet","what","wheat","wheel","when","where","while","whisper","white","whole","whom","wide","widely","wife","wild","will","willing","wind","window","wine","wing","winner","winter","wire","wisdom","wise","wish","withdraw","within","without","witness","woman","wonder","wood","wooden","word","work","worker","world","worried","worry","worse","worst","worth","would","wound","wrap","write","writer","wrong",
"yard","yeah","year","yell","yellow","yes","yesterday","yield","young","yours","youth","zone","zero"
}
local _0xG2="https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt"local _0xG3=game:HttpGet(_0xG2)local _0xG4={}
for _0xW in string.gmatch(_0xG3,"%S+") do if #_0xW>=3 and #_0xW<=12 then _0x._____((_0xG4),string.lower(_0xW))end end
local _0xG5={}for _0xK,_0xW in _0x.___________(_0xG1) do for _0xL=1,_0x.________((4),#_0xW) do local _0xP=_0x.___(_0xW,1,_0xL)if not _0xG5[_0xP] then _0xG5[_0xP]={}end;_0x._____((_0xG5[_0xP]),_0xW)end end
local _0xG6={}for _0xK,_0xW in _0x.___________(_0xG4) do for _0xL=1,_0x.________((4),#_0xW) do local _0xP=_0x.___(_0xW,1,_0xL)if not _0xG6[_0xP] then _0xG6[_0xP]={}end;_0x._____((_0xG6[_0xP]),_0xW)end end
_0xC3.Text=_0xA("\x55\x4c\x4e\x4b\x60\x27\x34")..#_0xG1.."+"..#_0xG4..")"_0xC2.BackgroundColor3=Color3.fromRGB(60,180,75)
local function _0xH1()local _0xO,_0xR=_0x.____________(function()return _0x4.MatchResults.Frame.Visible end)return _0xO and _0xR end
local function _0xH2()local _0xO,_0xR=_0x.____________(function()return _0x.____(_0x4.InGame.Frame.Type.Text:lower(),_0x5:lower())~=nil end)return _0xO and _0xR end
local function _0xH3()local _0xO,_0xR=_0x.____________(function()return _0x4.InGame.Frame.Visible end)return _0xO and _0xR end
local function _0xH4()local _0xO,_0xR=_0x.____________(function()local _0xF=_0x4.InGame.Frame.CurrentWord;local _0xT={};local _0xI=1;while true do local _0xS=_0xF:FindFirstChild(_0x._________(_0xI))if not _0xS then break end;local _0xL=_0xS:FindFirstChild(_0xA("\x5b\x70\x87\x87\x70\x81"))if _0xL and _0xL.Text and _0xL.Text~="..." and _0xL.Text~="" then _0x._____((_0xT),_0xL.Text)else break end;_0xI=_0xI+1 end;return _0x.______(_0xT):lower()end)return _0xO and _0xR or "" end
local function _0xH5(_0xP)if _0xG5[_0xP] then for _0xK,_0xW in _0x.___________(_0xG5[_0xP]) do if not _0xF6[_0xW] and not _0xF7[_0xW] then _0xF7[_0xW]=true;return _0xW end end end;if _0xG6[_0xP] then for _0xK,_0xW in _0x.___________(_0xG6[_0xP]) do if not _0xF6[_0xW] and not _0xF7[_0xW] then _0xF7[_0xW]=true;return _0xW end end end;return nil end
local function _0xH6()_0x._______________(_0xF2+_0x._______()* (_0xF2*0.8))end
local function _0xH7(_0xK)_0x1:SendKeyEvent(true,_0xK,false,game)_0x._______________(0.03)_0x1:SendKeyEvent(false,_0xK,false,game)end
local function _0xH8(_0xW,_0xPL)for _0xI=_0xPL+1,#_0xW do local _0xCH=_0x.___(_0xW,_0xI,_0xI)_0xH7(Enum.KeyCode[string.upper(_0xCH)])_0x._______________(0.06+_0x._______()* 0.12)end;_0x._______________(0.2+_0x._______()* 0.4)_0xH7(Enum.KeyCode.Return)end
local function _0xH9(_0xN)for _0xI=1,_0xN do _0xH7(Enum.KeyCode.Backspace)_0x._______________(0.04)end end
local function _0xHA()_0x.____________(function()local _0xDM=_0x4:FindFirstChild(_0xA("\x4b\x74\x82\x85\x79\x6e\x8c\x5c\x6e\x87\x6e\x71"))if not _0xDM then return end;local _0xM=_0xDM.Frame:FindFirstChild(_0xA("\x5c\x6e\x87\x6e\x71\x70\x82"))if not _0xM then return end;for _0xK,_0xMT in _0x.___________(_0xM:GetChildren()) do if _0xMT:IsA(_0xA("\x57\x70\x8b\x87\x47\x88\x87\x87\x84\x83")) then local _0xTL=_0xMT:FindFirstChild(_0xA("\x57\x74\x87\x79\x70"))if _0xTL and _0x.____(_0xTL.Text,_0xA("\x5b\x6e\x82\x87\x27\x5b\x70\x87\x87\x70\x81")) then local _0xPS=_0xMT:FindFirstChild(_0xA("\x5f\x79\x6e\x8c\x70\x81\x82"))if _0xPS then for _0xK2,_0xSL in _0x.___________(_0xPS:GetChildren()) do local _0xDT=_0xSL:FindFirstChild(_0xA("\x4b\x84\x87\x82"))if _0xDT and _0xDT.Text=="..." then for _0xK3,_0xCN in _0x.___________(getconnections(_0xMT.MouseButton1Click)) do _0xCN:Fire()end;return end end end end end end end)end
_0xE1.MouseButton1Click:Connect(function()_0xF1=not _0xF1;if _0xF1 then _0xE1.Text=_0xA("\x56\x57\x52\x5f");_0xE1.BackgroundColor3=Color3.fromRGB(240,60,60)_0xC3.Text=_0xA("\x4e\x4a\x57\x52\x59\x4c");_0xC2.BackgroundColor3=Color3.fromRGB(60,240,75)else _0xE1.Text=_0xA("\x56\x57\x4e\x55\x57");_0xE1.BackgroundColor3=Color3.fromRGB(88,101,242)_0xC3.Text=_0xA("\x5f\x4e\x58\x56\x4c\x4b");_0xC2.BackgroundColor3=Color3.fromRGB(240,180,40)end end)
for _0xK,_0xBN in _0x.___________(_0xC1:GetChildren()) do if _0xBN:IsA(_0xA("\x57\x70\x8b\x87\x47\x88\x87\x87\x84\x83")) and (_0xBN.Name==_0xE3[1][1] or _0xBN.Name==_0xE3[2][1] or _0xBN.Name==_0xE3[3][1]) then _0xBN.MouseButton1Click:Connect(function()for _0xK2,_0xB2 in _0x.___________(_0xC1:GetChildren()) do if _0xB2:IsA(_0xA("\x57\x70\x8b\x87\x47\x88\x87\x87\x84\x83")) and (_0xB2.Name==_0xE3[1][1] or _0xB2.Name==_0xE3[2][1] or _0xB2.Name==_0xE3[3][1]) then _0xB2.BackgroundColor3=Color3.fromRGB(38,38,50)end end;_0xBN.BackgroundColor3=Color3.fromRGB(88,101,242)for _0xK2,_0xS in _0x.___________(_0xE3) do if _0xS[1]==_0xBN.Name then _0xF2=_0xS[2];_0xE2.Text=_0xA("\x56\x5f\x4c\x4c\x4b\x3b\x27").._0xBN.Name end end end)end end
_0xB4.MouseButton1Click:Connect(function()_0xF1=false;_0x7:Destroy()end)
while _0x._______________(0.3) do
    if not _0xF1 then continue end
    if _0xH1() then
        if not _0xF8 then _0xF8=true;_0xF6={};_0xC7.Text=_0xA("\x5c\x4e\x57\x4a\x51\x27\x52\x59\x4c\x55");_0xC3.Text=_0xA("\x5c\x4e\x57\x4a\x51\x27\x4c\x53\x4b\x4c\x4b");_0xC2.BackgroundColor3=Color3.fromRGB(240,180,40)_0xC4.Text=_0xA("\x5e\x84\x81\x6f\x82\x27\x81\x70\x82\x70\x87")end
        continue
    else _0xF8=false end
    if _0xH3() then
        if _0xH2() then
            _0xC3.Text=_0xA("\x5c\x60\x27\x57\x58\x55\x53");_0xC2.BackgroundColor3=Color3.fromRGB(60,240,75)_0xC4.Text=_0xA("\x5f\x79\x6e\x8c\x74\x83\x72\x33\x33\x33");_0xC4.TextColor3=Color3.fromRGB(60,240,75)
            local _0xPR=_0xH4()if _0xPR=="" then continue end
            _0xF7={};_0xF5=_0xF5+1;_0xD4.Text=_0x._________(_0xF5)_0xC6.Text=_0xA("\x5f\x55\x4c\x49\x52\x5d\x3b\x27")..string.upper(_0xPR)
            local _0xAT=0
            while _0xH2() and _0xAT<10 do
                _0xAT=_0xAT+1
                local _0xWD=_0xH5(_0xPR)
                if not _0xWD then _0xC7.Text=_0xA("\x53\x52\x27\x5e\x52\x55\x4b\x56\x27\x5b\x4c\x49\x57");break end
                if _0xAT==1 then _0xC7.Text=string.upper(_0xWD);_0xH6()
                else _0xF4=_0xF4+1;_0xD3.Text=_0x._________(_0xF4)_0xC7.Text=string.upper(_0xWD).." (retry ".._0x._________(_0xAT-1)..")";_0x._______________(0.4+_0x._______()* 0.6)end
                _0xH8(_0xWD,#_0xPR);_0xF3=_0xF3+1;_0xD2.Text=_0x._________(_0xF3)
                _0x._______________(1.2)
                if not _0xH2() then _0xF6[_0xWD]=true;_0xC7.Text=string.upper(_0xWD).." OK";break end
                _0xH9(#_0xWD-#_0xPR);_0x._______________(0.3)
            end
        else
            _0xC3.Text=_0xA("\x5e\x4e\x52\x57\x52\x53\x50");_0xC2.BackgroundColor3=Color3.fromRGB(88,101,242)
            _0x.____________(function()local _0xON=string.match(_0x4.InGame.Frame.Type.Text,"^(.+),")_0xC4.Text="Turn: "..(_0xON or "?")_0xC4.TextColor3=Color3.fromRGB(140,140,160)end)
        end
    else
        _0xC3.Text=_0xA("\x56\x4c\x4e\x55\x4a\x51\x52\x53\x50\x27\x5c\x4e\x57\x4a\x51\x33\x33\x33");_0xC2.BackgroundColor3=Color3.fromRGB(240,180,40)_0xC4.Text="";_0xHA();_0x._______________(2)
    end
end
